### ISSUE TITLE
Does it have MapMatching feature for Android?

### ISSUE THREAD

**Issue by anonym24** [CartoType/CartoType-Public-5-4#1]
Example: https://farm1.staticflickr.com/530/18518221448_5752e8ab30_o.gif

https://en.wikipedia.org/wiki/Map_matching

**Comment by GrahamAsher** [comment]
Yes: ReadRouteFromXml will match a GPX track to the map. For future questions please use the 'contact' page in the CartoType web site, not this issue tracking system.

**Comment by anonym24** [comment]
What do you mean from XML? Can it match raw GPS points to the map from ArrayList?

**Comment by GrahamAsher** [comment]
This case is now closed. Please send further questions using this web page: http://www.cartotype.com/contact.
